OC.L10N.register(
    "integration_replicate",
    {
    "Bad HTTP method" : "Неверный метод HTTP",
    "Bad credentials" : "Неверные учётные данные",
    "The Replicate integration app provides a SpeechToText provider, a Text processing provider and an Image generation provider.\n\n⚠️ The smart pickers have been removed from this app\nas they are now included in the [Assistant app](https://apps.nextcloud.com/apps/assistant).\n\n## Ethical AI Rating\n### Speech-to-Text Rating: 🟡\n\nPositive:\n* The software for training and inference of this model is open source\n* The trained model is freely available, and thus can be run on-premises\n\nNegative:\n* The training data is not freely available, limiting the ability of external parties to check and correct for bias or optimise the model’s performance and CO2 usage.\n\n### Text processing Rating\n\nThe rating depends on the model you select to use.\n\n### Image generation Rating\n\nThe rating depends on the model you select to use.\n\nLearn more about the Nextcloud Ethical AI Rating [in our blog](https://nextcloud.com/blog/nextcloud-ethical-ai-rating/)." : "Приложение интеграции Replicate предоставляет поставщика SpeechToText, поставщика обработки текста и поставщика генерации изображений.\n\n⚠️ Умные селекторы были удалены из этого приложения,\nтак как теперь они включены в [приложение Assistant](https://apps.nextcloud.com/apps/assistant).\n\n## Рейтинг этического ИИ\n### Рейтинг преобразования речи в текст: 🟡\n\nПоложительные:\n* Программное обеспечение для обучения и вывода этой модели имеет открытый исходный код\n* Обученная модель находится в свободном доступе и, таким образом, может быть запущена локально\n\nОтрицательные:\n* Данные для обучения не находятся в свободном доступе, что ограничивает возможность внешних сторон проверять и исправлять смещения или оптимизировать производительность модели и использование CO2.\n\n### Рейтинг обработки текста\n\nРейтинг зависит от выбранной вами модели.\n\n### Рейтинг генерации изображений\n\nРейтинг зависит от выбранной вами модели.",
    "Replicate API token" : "Репликация токена API",
    "You can create a free API token on https://replicate.com" : "Вы можете создать бесплатный токен API на https://rescribe.com",
    "Text generation" : "Генерация текста",
    "Image generation" : "Создание изображений",
    "Small" : "Маленькая",
    "Medium" : "Средняя",
    "Large" : "Большая",
    "Extra parameters are model-specific. For example: {\"max_new_tokens\":128,\"temperature\":0.7}" : "Дополнительные параметры зависят от модели. Например: {\"max_new_tokens\":128,\"temperature\":0.7}"
},
"nplurals=4; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<12 || n%100>14) ? 1 : n%10==0 || (n%10>=5 && n%10<=9) || (n%100>=11 && n%100<=14)? 2 : 3);");
