# This workflow is provided via the organization template repository
#
# https://github.com/nextcloud/.github
# https://docs.github.com/en/actions/learn-github-actions/sharing-workflows-with-your-organization

name: Psalm static analysis

on:
  pull_request:
    paths:
      - .github/workflows/psalm.yml
      - appinfo/**
      - composer.*
      - lib/**
      - templates/**
      - tests/**
  push:
    branches:
      - main
      - stable*
      - test
    paths:
      - .github/workflows/psalm.yml
      - appinfo/**
      - composer.*
      - lib/**
      - templates/**
      - tests/**

concurrency:
  group: psalm-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  static-analysis:
    runs-on: ubuntu-latest

    name: Psalm check
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Set up php
        uses: shivammathur/setup-php@c5fc0d8281aba02c7fda07d3a70cc5371548067d # v2
        with:
          php-version: 8.2
          coverage: none
          ini-file: development
          extensions: mbstring, iconv, fileinfo, intl, sqlite, pdo_sqlite, gd, zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Install dependencies
        run: composer i

      - name: Run coding standards check
        run: composer run psalm
